### ISSUE TITLE
Apps in app library does not start on windows

### ISSUE THREAD

**Issue by idursun** [fabric8io/jube#264]
When I try to start an app (elasticsearch or kibana) in a container I get the following error:
```
Failed to create pod: elasticsearch-controller-1. Failed to resolve mvn:io.fabric8.jube.images.fabric8/elasticsearch-k8s/1.4.4/zip/image. org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact io.fabric8.jube.images.fabric8:elasticsearch-k8s:zip:image:1.4.4 in central (http://repo1.maven.org/maven2)
```

Environment variables check: ok
```bash
KUBERNETES_MASTER="http://localhost:8585/"
FABRIC8_CONSOLE="http://localhost:8585/hawtio/"
```
Is it normal these apps not to work right away or am I missing some settings on my box?

**Comment by jstrachan** [comment]
I'm afraid we don't yet have a properly created jube image for elasticsearch. The quickstarts and Fabric8 MQ apps should work fine though

**Comment by idursun** [comment]
Thanks, it is nice to know that this is not configuration related at least.
